//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACarStaj.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAracAlimLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblAracAlimLog()
        {
            this.TblAraclar1 = new HashSet<TblAraclar>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AracNo { get; set; }
        public Nullable<int> TeslimEden { get; set; }
        public Nullable<int> TeslimAlan { get; set; }
        public string AlanAd { get; set; }
        public string AlanSoyad { get; set; }
        public string AlanTelefon { get; set; }
        public Nullable<int> Ehliyet { get; set; }
        public Nullable<System.DateTime> AlimTarihi { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public Nullable<int> Durum { get; set; }
        public Nullable<int> KiralamaUcreti { get; set; }
    
        public virtual TblAraclar TblAraclar { get; set; }
        public virtual TblEhliyetTipleri TblEhliyetTipleri { get; set; }
        public virtual TblPersonel TblPersonel { get; set; }
        public virtual TblPersonel TblPersonel1 { get; set; }
        public virtual TblDurum TblDurum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAraclar> TblAraclar1 { get; set; }
    }
}
