//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACarStaj.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAraclar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblAraclar()
        {
            this.TblAracAlimLog = new HashSet<TblAracAlimLog>();
            this.TblHasarLog = new HashSet<TblHasarLog>();
        }
    
        public int ID { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Plaka { get; set; }
        public Nullable<System.DateTime> SonBakimTarihi { get; set; }
        public Nullable<System.DateTime> SiradakiBakimTarihi { get; set; }
        public Nullable<int> Durum { get; set; }
        public Nullable<int> Ucret { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAracAlimLog> TblAracAlimLog { get; set; }
        public virtual TblDurum TblDurum { get; set; }
        public virtual TblAracAlimLog TblAracAlimLog1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblHasarLog> TblHasarLog { get; set; }
    }
}
